#!/usr/bin/env python

import sys

try:
    from coverage.cmdline import main
except ImportError as exc:
    try:
        from coverage import main
    except ImportError:
        sys.exit("Error: failed to run coverage: {0}".format(exc))

if __name__ == '__main__':
    sys.exit(main())
